# Generated by Django 6.0.6 on 2026-06-26 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_login_date_userprofile_xp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panic_sell_count', models.IntegerField(default=0)),
                ('fomo_buy_count', models.IntegerField(default=0)),
                ('overtrading_count', models.IntegerField(default=0)),
                ('hold_loser_count', models.IntegerField(default=0)),
                ('sell_winner_early_count', models.IntegerField(default=0)),
                ('poor_diversification_count', models.IntegerField(default=0)),
                ('disciplined_hold_count', models.IntegerField(default=0)),
                ('dominant_weakness', models.CharField(blank=True, default='', max_length=50)),
                ('last_analysis_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_level', models.CharField(default='beginner', max_length=20)),
                ('concepts_taught', models.JSONField(default=list)),
                ('concepts_mastered', models.JSONField(default=list)),
                ('current_topic', models.CharField(blank=True, default='', max_length=50)),
                ('next_topic', models.CharField(blank=True, default='', max_length=50)),
                ('total_lessons_received', models.IntegerField(default=0)),
                ('last_lesson_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorCardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('stock_symbol', models.CharField(blank=True, default='', max_length=20)),
                ('card_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
