# Generated by Django 6.0.6 on 2026-07-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_behaviourprofile_learningprofile_mentorcardcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=15),
        ),
    ]
