# Generated by Django 6.0.6 on 2026-06-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_close', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
